// <auto-generated />
using System;
using GarmentShop.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarmentShop.Infrastructure.Migrations
{
    [DbContext(typeof(GarmentShopDbContext))]
    partial class GarmentShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarmentShop.Domain.AuthenticationAggregate.Authentication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RegisteredUsers");
                });

            modelBuilder.Entity("GarmentShop.Domain.BrandAggregate.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("GarmentShop.Domain.Common.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("GarmentShop.Domain.Common.Outbox.OutboxMessageConsumer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessageConsumers");
                });

            modelBuilder.Entity("GarmentShop.Domain.GarmentAggregate.Garment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("GarmentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Garments");
                });

            modelBuilder.Entity("GarmentShop.Domain.GarmentCategoryAggregate.GarmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GarmentCategories");
                });

            modelBuilder.Entity("GarmentShop.Domain.GarmentTypeAggregate.GarmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("GarmentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GarmentTypes");
                });

            modelBuilder.Entity("GarmentShop.Domain.SaleAggregate.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("GarmentShop.Domain.UserAggregate.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("729d3423-6250-46fe-aaee-b031e7e13ee3"),
                            CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9791),
                            ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9798),
                            Name = "Customer",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("ba6d0919-1e52-449a-a4b5-3d196eaf28e0"),
                            CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9802),
                            ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9804),
                            Name = "Manager",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("274948e2-efa8-4248-9f1f-5073ae056d9d"),
                            CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9807),
                            ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9809),
                            Name = "Admin",
                            Type = 2
                        });
                });

            modelBuilder.Entity("GarmentShop.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GarmentShop.Domain.SaleAggregate.Sale", b =>
                {
                    b.OwnsMany("GarmentShop.Domain.SaleAggregate.Entities.Order", "Orders", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SaleOrderId");

                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ModifiedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id", "SaleId");

                            b1.HasIndex("SaleId");

                            b1.ToTable("SaleOrders", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SaleId");

                            b1.OwnsOne("GarmentShop.Domain.SaleAggregate.ValueObjects.Invoice", "Invoice", b2 =>
                                {
                                    b2.Property<Guid>("OrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("OrderSaleId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("OtherCharges")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("OtherCharges");

                                    b2.Property<decimal>("ShippingAndHandling")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("ShippingAndHandling");

                                    b2.Property<decimal>("Tax")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("Tax");

                                    b2.Property<decimal>("TotalCost")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("TotalCost");

                                    b2.HasKey("OrderId", "OrderSaleId");

                                    b2.ToTable("SaleOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderId", "OrderSaleId");
                                });

                            b1.OwnsOne("GarmentShop.Domain.SaleAggregate.ValueObjects.Payment", "Payment", b2 =>
                                {
                                    b2.Property<Guid>("OrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("OrderSaleId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)");

                                    b2.Property<DateTime>("Date")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("Method")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Method");

                                    b2.HasKey("OrderId", "OrderSaleId");

                                    b2.ToTable("SaleOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderId", "OrderSaleId");
                                });

                            b1.OwnsMany("GarmentShop.Domain.SaleAggregate.Entities.OrderItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("OrderItemId");

                                    b2.Property<Guid>("SaleOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("SaleId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("CreatedDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<Guid>("GarmentId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("GarmentId");

                                    b2.Property<DateTime>("ModifiedDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("int")
                                        .HasColumnName("Quantity");

                                    b2.Property<decimal>("UnitPrice")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("UnitPrice");

                                    b2.HasKey("Id", "SaleOrderId", "SaleId");

                                    b2.HasIndex("SaleOrderId", "SaleId");

                                    b2.ToTable("OrderItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SaleOrderId", "SaleId");
                                });

                            b1.Navigation("Invoice")
                                .IsRequired();

                            b1.Navigation("Items");

                            b1.Navigation("Payment")
                                .IsRequired();
                        });

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GarmentShop.Domain.UserAggregate.Entities.Role", b =>
                {
                    b.OwnsMany("GarmentShop.Domain.UserAggregate.Entities.Permission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PermissionId");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ModifiedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");

                            b1.Property<int>("Type")
                                .HasMaxLength(50)
                                .HasColumnType("int")
                                .HasColumnName("Type");

                            b1.HasKey("Id", "RoleId");

                            b1.HasIndex("RoleId");

                            b1.ToTable("RolePermissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoleId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("15d1cf25-485d-4f4b-82c1-a46559de30d5"),
                                    RoleId = new Guid("729d3423-6250-46fe-aaee-b031e7e13ee3"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9268),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9321),
                                    Name = "AddToCart",
                                    Type = 0
                                },
                                new
                                {
                                    Id = new Guid("5dec5f96-76ef-4c87-8aba-b06aed16aaef"),
                                    RoleId = new Guid("729d3423-6250-46fe-aaee-b031e7e13ee3"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9326),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9328),
                                    Name = "PlaceOrder",
                                    Type = 1
                                },
                                new
                                {
                                    Id = new Guid("5faa0d50-4753-4e23-9cff-bc82deed6ceb"),
                                    RoleId = new Guid("729d3423-6250-46fe-aaee-b031e7e13ee3"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9345),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9347),
                                    Name = "ViewOrderHistory",
                                    Type = 2
                                },
                                new
                                {
                                    Id = new Guid("4a692ebf-3664-4f22-88c6-a0b8c46e3357"),
                                    RoleId = new Guid("729d3423-6250-46fe-aaee-b031e7e13ee3"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9352),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9354),
                                    Name = "UpdateShippingAddress",
                                    Type = 3
                                },
                                new
                                {
                                    Id = new Guid("9ab90b85-3e3b-4042-bec2-20bbf4606fa0"),
                                    RoleId = new Guid("ba6d0919-1e52-449a-a4b5-3d196eaf28e0"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9358),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9360),
                                    Name = "EditItems",
                                    Type = 4
                                },
                                new
                                {
                                    Id = new Guid("736ffe87-d3b5-49a0-9f2b-b12d35e69d22"),
                                    RoleId = new Guid("ba6d0919-1e52-449a-a4b5-3d196eaf28e0"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9364),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9366),
                                    Name = "DeleteItems",
                                    Type = 5
                                },
                                new
                                {
                                    Id = new Guid("7d7b3a00-df3f-4ad7-8603-d22ba079b9c9"),
                                    RoleId = new Guid("ba6d0919-1e52-449a-a4b5-3d196eaf28e0"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9370),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9372),
                                    Name = "AddItems",
                                    Type = 6
                                },
                                new
                                {
                                    Id = new Guid("a98a8e44-4528-48c1-9578-2bcec0561432"),
                                    RoleId = new Guid("274948e2-efa8-4248-9f1f-5073ae056d9d"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9376),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9378),
                                    Name = "ManageCustomers",
                                    Type = 7
                                },
                                new
                                {
                                    Id = new Guid("04797320-c4b7-41e7-b6fb-2479c16b6cfb"),
                                    RoleId = new Guid("274948e2-efa8-4248-9f1f-5073ae056d9d"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9383),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9384),
                                    Name = "ManageUsers",
                                    Type = 8
                                },
                                new
                                {
                                    Id = new Guid("ed1764cf-dd7f-49d9-aeed-8e24e73129a7"),
                                    RoleId = new Guid("274948e2-efa8-4248-9f1f-5073ae056d9d"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9389),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9391),
                                    Name = "ManageRoles",
                                    Type = 9
                                },
                                new
                                {
                                    Id = new Guid("80bc6902-e761-48c6-8e86-38bfbc3650f7"),
                                    RoleId = new Guid("274948e2-efa8-4248-9f1f-5073ae056d9d"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9399),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9401),
                                    Name = "ManagePermissions",
                                    Type = 10
                                },
                                new
                                {
                                    Id = new Guid("0c873692-42d0-4379-b428-d6b6f1104fe4"),
                                    RoleId = new Guid("274948e2-efa8-4248-9f1f-5073ae056d9d"),
                                    CreatedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9406),
                                    ModifiedDate = new DateTime(2023, 2, 23, 15, 8, 18, 745, DateTimeKind.Local).AddTicks(9408),
                                    Name = "ManageOrders",
                                    Type = 11
                                });
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("GarmentShop.Domain.UserAggregate.User", b =>
                {
                    b.OwnsMany("GarmentShop.Domain.SaleAggregate.ValueObjects.SaleId", "SaleIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SaleId");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserSaleIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("GarmentShop.Domain.UserAggregate.Entities.UserRole", "Roles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("UserRoleId");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ModifiedDate")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id", "RoleId");

                            b1.HasIndex("RoleId");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserRoles", (string)null);

                            b1.HasOne("GarmentShop.Domain.UserAggregate.Entities.Role", "Role")
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.Navigation("Role");
                        });

                    b.OwnsOne("GarmentShop.Domain.UserAggregate.ValueObjects.UserDetailInformation", "Information", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address");

                            b1.Property<string>("City")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Country");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PhoneNumber");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("SaleIds");
                });
#pragma warning restore 612, 618
        }
    }
}
