// <auto-generated />
using System;
using GarmentShop.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarmentShop.Infrastructure.Migrations
{
    [DbContext(typeof(GarmentShopDbContext))]
    partial class GarmentShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarmentShop.Domain.AuthenticationAggregate.Authentication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RegisteredUsers");
                });

            modelBuilder.Entity("GarmentShop.Domain.BrandAggregate.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("GarmentShop.Domain.Common.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Error")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("GarmentShop.Domain.GarmentAggregate.Garment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("int");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("GarmentTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Garments");
                });

            modelBuilder.Entity("GarmentShop.Domain.GarmentCategoryAggregate.GarmentCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GarmentCategories");
                });

            modelBuilder.Entity("GarmentShop.Domain.GarmentTypeAggregate.GarmentType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("GarmentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GarmentTypes");
                });

            modelBuilder.Entity("GarmentShop.Domain.SaleAggregate.Sale", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Sales", (string)null);
                });

            modelBuilder.Entity("GarmentShop.Domain.UserAggregate.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<int>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("873299d9-e0be-4fc2-89ff-7952ae603174"),
                            CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5854),
                            ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5860),
                            Name = "Customer",
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("2d25cec7-d3d6-449d-a03d-70b8d0f27b92"),
                            CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5864),
                            ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5865),
                            Name = "Manager",
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("94995d3a-f7f4-4e9c-9f25-c15a12be955f"),
                            CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5868),
                            ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5870),
                            Name = "Admin",
                            Type = 2
                        });
                });

            modelBuilder.Entity("GarmentShop.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GarmentShop.Domain.SaleAggregate.Sale", b =>
                {
                    b.OwnsMany("GarmentShop.Domain.SaleAggregate.Entities.Order", "Orders", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SaleOrderId");

                            b1.Property<Guid>("SaleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ModifiedDate")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id", "SaleId");

                            b1.HasIndex("SaleId");

                            b1.ToTable("SaleOrders", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("SaleId");

                            b1.OwnsOne("GarmentShop.Domain.SaleAggregate.ValueObjects.Invoice", "Invoice", b2 =>
                                {
                                    b2.Property<Guid>("OrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("OrderSaleId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("OtherCharges")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("OtherCharges");

                                    b2.Property<decimal>("ShippingAndHandling")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("ShippingAndHandling");

                                    b2.Property<decimal>("Tax")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("Tax");

                                    b2.Property<decimal>("TotalCost")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("TotalCost");

                                    b2.HasKey("OrderId", "OrderSaleId");

                                    b2.ToTable("SaleOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderId", "OrderSaleId");
                                });

                            b1.OwnsOne("GarmentShop.Domain.SaleAggregate.ValueObjects.Payment", "Payment", b2 =>
                                {
                                    b2.Property<Guid>("OrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("OrderSaleId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)");

                                    b2.Property<DateTime>("Date")
                                        .HasColumnType("datetime2");

                                    b2.Property<string>("Method")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("nvarchar(50)")
                                        .HasColumnName("Method");

                                    b2.HasKey("OrderId", "OrderSaleId");

                                    b2.ToTable("SaleOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderId", "OrderSaleId");
                                });

                            b1.OwnsMany("GarmentShop.Domain.SaleAggregate.Entities.OrderItem", "Items", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("OrderItemId");

                                    b2.Property<Guid>("SaleOrderId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("SaleId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<DateTime>("CreatedDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<Guid>("GarmentId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("GarmentId");

                                    b2.Property<DateTime>("ModifiedDate")
                                        .HasColumnType("datetime2");

                                    b2.Property<int>("Quantity")
                                        .HasColumnType("int")
                                        .HasColumnName("Quantity");

                                    b2.Property<decimal>("UnitPrice")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("UnitPrice");

                                    b2.HasKey("Id", "SaleOrderId", "SaleId");

                                    b2.HasIndex("SaleOrderId", "SaleId");

                                    b2.ToTable("OrderItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("SaleOrderId", "SaleId");
                                });

                            b1.Navigation("Invoice")
                                .IsRequired();

                            b1.Navigation("Items");

                            b1.Navigation("Payment")
                                .IsRequired();
                        });

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GarmentShop.Domain.UserAggregate.Entities.Role", b =>
                {
                    b.OwnsMany("GarmentShop.Domain.UserAggregate.Entities.Permission", "Permissions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PermissionId");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ModifiedDate")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Name");

                            b1.Property<int>("Type")
                                .HasMaxLength(50)
                                .HasColumnType("int")
                                .HasColumnName("Type");

                            b1.HasKey("Id", "RoleId");

                            b1.HasIndex("RoleId");

                            b1.ToTable("RolePermissions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RoleId");

                            b1.HasData(
                                new
                                {
                                    Id = new Guid("e8363d05-f28d-4447-b022-953f8f63d7ce"),
                                    RoleId = new Guid("873299d9-e0be-4fc2-89ff-7952ae603174"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5332),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5396),
                                    Name = "AddToCart",
                                    Type = 0
                                },
                                new
                                {
                                    Id = new Guid("39c92b90-1af0-496f-9de5-0fa7babcab37"),
                                    RoleId = new Guid("873299d9-e0be-4fc2-89ff-7952ae603174"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5401),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5403),
                                    Name = "PlaceOrder",
                                    Type = 1
                                },
                                new
                                {
                                    Id = new Guid("0d618911-8591-45ee-8c56-ea05820a5390"),
                                    RoleId = new Guid("873299d9-e0be-4fc2-89ff-7952ae603174"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5407),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5409),
                                    Name = "ViewOrderHistory",
                                    Type = 2
                                },
                                new
                                {
                                    Id = new Guid("3787eecc-7b14-4c66-886e-cf5a3aa14270"),
                                    RoleId = new Guid("873299d9-e0be-4fc2-89ff-7952ae603174"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5413),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5415),
                                    Name = "UpdateShippingAddress",
                                    Type = 3
                                },
                                new
                                {
                                    Id = new Guid("24661828-46b5-456b-a7e8-b40e2ce4b660"),
                                    RoleId = new Guid("2d25cec7-d3d6-449d-a03d-70b8d0f27b92"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5419),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5421),
                                    Name = "EditItems",
                                    Type = 4
                                },
                                new
                                {
                                    Id = new Guid("4fa7da2b-5364-4c63-a095-ddb805f38946"),
                                    RoleId = new Guid("2d25cec7-d3d6-449d-a03d-70b8d0f27b92"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5433),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5434),
                                    Name = "DeleteItems",
                                    Type = 5
                                },
                                new
                                {
                                    Id = new Guid("53543dc3-b5a6-41f1-83ac-90e4e54778c9"),
                                    RoleId = new Guid("2d25cec7-d3d6-449d-a03d-70b8d0f27b92"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5439),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5440),
                                    Name = "AddItems",
                                    Type = 6
                                },
                                new
                                {
                                    Id = new Guid("22668925-fad1-4bd2-8fce-5152157b8b06"),
                                    RoleId = new Guid("94995d3a-f7f4-4e9c-9f25-c15a12be955f"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5444),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5446),
                                    Name = "ManageCustomers",
                                    Type = 7
                                },
                                new
                                {
                                    Id = new Guid("ae370106-f7ff-4c78-9b7c-e691a4385913"),
                                    RoleId = new Guid("94995d3a-f7f4-4e9c-9f25-c15a12be955f"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5450),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5452),
                                    Name = "ManageUsers",
                                    Type = 8
                                },
                                new
                                {
                                    Id = new Guid("a95eae0f-c7f4-408d-8010-b3d031bd837f"),
                                    RoleId = new Guid("94995d3a-f7f4-4e9c-9f25-c15a12be955f"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5456),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5458),
                                    Name = "ManageRoles",
                                    Type = 9
                                },
                                new
                                {
                                    Id = new Guid("9925f28f-4606-4cef-9117-19693fa49c5c"),
                                    RoleId = new Guid("94995d3a-f7f4-4e9c-9f25-c15a12be955f"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5462),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5463),
                                    Name = "ManagePermissions",
                                    Type = 10
                                },
                                new
                                {
                                    Id = new Guid("5f5c9eeb-b41d-4e67-a34b-4c0bf93ec9a0"),
                                    RoleId = new Guid("94995d3a-f7f4-4e9c-9f25-c15a12be955f"),
                                    CreatedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5467),
                                    ModifiedDate = new DateTime(2023, 2, 17, 14, 9, 19, 432, DateTimeKind.Local).AddTicks(5469),
                                    Name = "ManageOrders",
                                    Type = 11
                                });
                        });

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("GarmentShop.Domain.UserAggregate.User", b =>
                {
                    b.OwnsMany("GarmentShop.Domain.SaleAggregate.ValueObjects.SaleId", "SaleIds", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SaleId");

                            b1.HasKey("Id");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserSaleIds", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsMany("GarmentShop.Domain.UserAggregate.Entities.UserRole", "Roles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("UserRoleId");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("CreatedDate")
                                .HasColumnType("datetime2");

                            b1.Property<DateTime>("ModifiedDate")
                                .HasColumnType("datetime2");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id", "RoleId");

                            b1.HasIndex("RoleId");

                            b1.HasIndex("UserId");

                            b1.ToTable("UserRoles", (string)null);

                            b1.HasOne("GarmentShop.Domain.UserAggregate.Entities.Role", "Role")
                                .WithMany()
                                .HasForeignKey("RoleId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.Navigation("Role");
                        });

                    b.OwnsOne("GarmentShop.Domain.UserAggregate.ValueObjects.UserDetailInformation", "Information", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Address")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Address");

                            b1.Property<string>("City")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Country");

                            b1.Property<string>("FirstName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("LastName");

                            b1.Property<string>("PhoneNumber")
                                .HasMaxLength(30)
                                .HasColumnType("nvarchar(30)")
                                .HasColumnName("PhoneNumber");

                            b1.Property<string>("ZipCode")
                                .HasMaxLength(15)
                                .HasColumnType("nvarchar(15)")
                                .HasColumnName("ZipCode");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("Roles");

                    b.Navigation("SaleIds");
                });
#pragma warning restore 612, 618
        }
    }
}
